GoldenBookWeb/Areas/Admin/Controllers/CoverTypeController.cs
using GoldenBook.DataAccess.Repository.IRepository;
using GoldenBook.Models;
using GoldenBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GoldenBook.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CoverTypeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CoverTypeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<CoverType> objCoverTypeList = _unitOfWork.CoverType.GetAll();
            return View(objCoverTypeList);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.CoverType.Add(obj);
                _unitOfWork.Save();
                TempData["Success"] = "Cover Type created successfully!";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var coverTypefromDb = _unitOfWork.CoverType.GetFirstOrDefault(u=>u.Id==id);

            if (coverTypefromDb == null)
            {
                return NotFound();
            }
            return View(coverTypefromDb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.CoverType.Update(obj);
                _unitOfWork.Save();
                TempData["Success"] = "Cover Type updated successfully!";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var coverTypefromDb = _unitOfWork.CoverType.GetFirstOrDefault(u => u.Id == id);

            if (coverTypefromDb == null)
            {
                return NotFound();
            }
            return View(coverTypefromDb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(CoverType obj)
        {
            _unitOfWork.CoverType.Remove(obj);
            _unitOfWork.Save();
            TempData["Success"] = "Cover Type deleted successfully!";
            return RedirectToAction("Index");
        }
    }
}

GoldenBookWeb/Areas/Admin/Controllers/ProductController.cs
using GoldenBook.DataAccess.Repository.IRepository;
using GoldenBook.Models.ViewModels;
using GoldenBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GoldenBook.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;

        public ProductController(IUnitOfWork unitOfWork,IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            ProductVM productVM = new()
            {
                Product = new(),
                CategoryList = _unitOfWork.Category.GetAll().Select(
                    u => new SelectListItem
                    {
                        Text = u.Name,
                        Value = u.Id.ToString()
                    }),
                CoverTypeList = _unitOfWork.CoverType.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                })

            };

            if (id == null || id == 0)
            {
                //insert
                //ViewBag.CategoryList = CategoryList;
                //ViewData["CoverTypeList"] = CoverTypeList;
                return View(productVM);
            }
            else
            {
                productVM.Product = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
                return View(productVM);
                //update
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM obj, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file!=null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"images\products");
                    var extension = Path.GetExtension(file.FileName);

                    if (obj.Product.ImageUrl != null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath,obj.Product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStreams = new FileStream(Path.Combine(uploads,fileName+extension),FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    obj.Product.ImageUrl = @"images\products\" + fileName + extension;
                }
                if (obj.Product.Id==0)
                {
                    _unitOfWork.Product.Add(obj.Product);
                }
                else
                {
                    _unitOfWork.Product.Update(obj.Product);
                }
                _unitOfWork.Save();
                TempData["Success"] = "Cover Type updated successfully!";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var productList = _unitOfWork.Product.GetAll(includeProperties:"Category,CoverType");
            return Json(new { data = productList });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var obj = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
            if (obj==null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            if (obj.ImageUrl != null)
            {
                var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
                if (System.IO.File.Exists(oldImagePath))
                {
                    System.IO.File.Delete(oldImagePath);
                }
            }

            _unitOfWork.Product.Remove(obj);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Deleted succesfully" });
        }
        #endregion
    }

}

GoldenBookWeb/Areas/Admin/Views/Product/Index.cshtml
<div class="cat-container">
    <div class="row pt-4">
        <div class="col-6">
            <h2>Product List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Product" asp-action="Upsert" class="btn btn-success"><i class="bi bi-file-earmark-plus"></i> &nbsp; Create new Product</a>
        </div>
    </div>
    <br />
    <table id="tblData" class="table table-bordered table-striped text-white" style="width:100%">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Author
                </th>
                <th>
                    ISBN
                </th>
                <th>
                    Price
                </th>
                <th>
                    Category
                </th>
                <th></th>
            </tr>
        </thead>
    </table>
</div>

@section Scripts{
    <script src="~/js/product.js"></script>
}

GoldenBookWeb/Areas/Admin/Views/Product/Upsert.cshtml
@model GoldenBook.Models.ViewModels.ProductVM

<form method="post" asp-action="Upsert" enctype="multipart/form-data">
    <input asp-for="Product.Id" hidden />
    <input asp-for="Product.ImageUrl" hidden />
    <div class="border p-3 row">
        <div class="row p-1">
            <h2>@(Model.Product.Id!=0 ? "Update" : "Create") Product</h2>
            <hr />
        </div>
        @* <div asp-validation-summary="All"></div>*@
        <div class="pb-2">
            <label asp-for="Product.Name"></label>
            <input asp-for="Product.Name" class="form-control" />
            <span asp-validation-for="Product.Name" class="text-danger"></span>
        </div>
        <div class="pb-2">
            <label asp-for="Product.Description"></label>
            <textarea asp-for="Product.Description" rows="3" class="form-control"></textarea>
            <span asp-validation-for="Product.Description" class="text-danger"></span>
        </div>
        <div class="pb-2 col-6">
            <label asp-for="Product.ISBN"></label>
            <input asp-for="Product.ISBN" class="form-control" />
            <span asp-validation-for="Product.ISBN" class="text-danger"></span>
        </div>
        <div class="pb-2 col-6">
            <label asp-for="Product.Author"></label>
            <input asp-for="Product.Author" class="form-control" />
            <span asp-validation-for="Product.Author" class="text-danger"></span>
        </div>
        <div class="pb-2 col-6">
            <label asp-for="Product.ListPrice"></label>
            <input asp-for="Product.ListPrice" class="form-control" />
            <span asp-validation-for="Product.ListPrice" class="text-danger"></span>
        </div>
        <div class="pb-2 col-6">
            <label asp-for="Product.Price"></label>
            <input asp-for="Product.Price" class="form-control" />
            <span asp-validation-for="Product.Price" class="text-danger"></span>
        </div>
        <div class="pb-2 col-6">
            <label asp-for="Product.Price5"></label>
            <input asp-for="Product.Price5" class="form-control" />
            <span asp-validation-for="Product.Price5" class="text-danger"></span>
        </div>
        <div class="pb-2 col-6">
            <label asp-for="Product.Price10"></label>
            <input asp-for="Product.Price10" class="form-control" />
            <span asp-validation-for="Product.Price10" class="text-danger"></span>
        </div>
        <div class="pb-2">
            <label asp-for="Product.ImageUrl"></label>
            <input type="file" name="file" id="uploadBox" class="form-control" />
        </div>
        <div class="pb-2 col-6">
            <label asp-for="Product.CategoryId"></label>
            <select asp-for="Product.CategoryId" asp-items="Model.CategoryList" class="form-select">
                <option disabled selected>--Select Category--</option>
            </select>
            <span asp-validation-for="Product.CategoryId" class="text-danger"></span>
        </div>
        <div class="pb-2 col-6">
            <label asp-for="Product.CoverTypeId"></label>
            <select asp-for="Product.CoverTypeId" asp-items="@Model.CoverTypeList" class="form-select">
                <option disabled selected>--Select Cover Type--</option>
            </select>
            <span asp-validation-for="Product.CoverTypeId" class="text-danger"></span>
        </div>
        <div class="col-12 pt-3">
            @if (Model.Product.Id != 0)
            {
                <button type="submit" class="btn btn-success">Update</button>
            }
            else
            {
                <button type="submit" onclick="return ValidateInput()" class="btn btn-success">Create</button>
            }
            <a asp-controller="CoverType" asp-action="Index" class="btn btn-info">Back to List</a>
        </div>
    </div>
</form>

@section Scripts{
    @{
    <partial name="_ValidationScriptsPartial.cshtml" />

    <script>
        function ValidateInput()
        {
            if(document.getElementById("uploadBox").value=="")
            {
                Swal.fire
                ({
                    icon: 'error',
                    title: 'Oops...',
                    text: 'Please upload an image!'
                })
            }
        }
    </script>
    }
}